import { MARKER } from "../lib/report"

/**
 * The GitHub workflows `init` writes. Plain string templates: the output is
 * short, and a YAML library would add a dependency to print two files.
 *
 * Every action is pinned to a commit SHA, with the tag in a comment, so a
 * moved tag cannot change what runs with a write token.
 */

export const ACTIONS = {
  checkout:
    "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1",
  setupNode:
    "actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0",
  setupBun:
    "oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0",
} as const

export type PackageManager = "bun" | "pnpm" | "yarn" | "npm"
export type WriteMode = "push" | "pr"

/** The branch the bot commits to in `pr` mode. */
export const REFRESH_BRANCH = "crap-check/refresh"

export interface HistoryWorkflowOptions {
  cron: string
  mode: WriteMode
  /** The branch the workflow checks out and writes back to. */
  branch: string
  /** The ref whose history is walked, such as `origin/main`. */
  ref: string
  outDir: string
  /** The package manager to install with, or `null` to skip the install. */
  install: PackageManager | null
  /** The pinned CLI invocation, such as `npx -y @gusfune/crap-check@0.1.0`. */
  cli: string
}

const INSTALL: Record<PackageManager, string> = {
  bun: "bun install --frozen-lockfile",
  // Corepack ships with Node 24 and reads `packageManager` from package.json.
  pnpm: "corepack enable && pnpm install --frozen-lockfile",
  yarn: "corepack enable && yarn install --immutable",
  npm: "npm ci",
}

/** Steps that install the repository's dependencies, so its coverage commands run. */
const installSteps = (install: PackageManager | null): string => {
  if (install === null) {
    return ""
  }

  const bun = install === "bun" ? `\n      - uses: ${ACTIONS.setupBun}\n` : ""

  return `${bun}
      # The coverage commands run the repository's own test suites.
      - run: ${INSTALL[install]}
`
}

const COMMIT = `git -c user.name='github-actions[bot]' \\
                -c user.email='41898282+github-actions[bot]@users.noreply.github.com' \\
                commit -m 'chore(crap-check): refresh the complexity history [skip ci]'`

/** Push mode: commit on top of the branch, rebuild on the new tip when it moves. */
const pushScript = ({ branch }: HistoryWorkflowOptions): string => `
          refresh
          if git diff --cached --quiet; then
            echo "Nothing changed."
            exit 0
          fi
          commit

          # A rejected fast-forward means somebody pushed during the run. Rebuild on
          # the new tip: regeneration cannot conflict on history.json, a rebase can.
          for attempt in 1 2 3; do
            if git push origin HEAD:refs/heads/${branch}; then
              echo "Landed on ${branch} on attempt $attempt."
              exit 0
            fi
            echo "${branch} moved during the run. Rebuilding on the new tip."
            git fetch --no-tags origin ${branch}
            git reset --hard FETCH_HEAD
            refresh
            if git diff --cached --quiet; then
              echo "The new tip already carries this data."
              exit 0
            fi
            commit
          done

          echo "::error::${branch} kept moving. Three pushes were rejected."
          exit 1`

/** PR mode: one bot branch, rewritten each run, and one open pull request. */
const prScript = ({ branch }: HistoryWorkflowOptions): string => `
          refresh
          if git diff --cached --quiet; then
            echo "Nothing changed."
            exit 0
          fi
          commit

          # The bot branch holds one commit on top of ${branch}, rebuilt every run.
          git push --force origin HEAD:refs/heads/${REFRESH_BRANCH}

          open=$(gh pr list --head ${REFRESH_BRANCH} --base ${branch} --state open --json number --jq length)
          if [ "$open" = "0" ]; then
            gh pr create --base ${branch} --head ${REFRESH_BRANCH} \\
              --title "chore(crap-check): refresh the complexity history" \\
              --body "Generated by crap-check. Merge to land this period's complexity data."
          fi`

export const renderHistoryWorkflow = (
  options: HistoryWorkflowOptions
): string => {
  const { cron, mode, branch, ref, outDir, install, cli } = options
  const isPr = mode === "pr"
  const remoteBranch =
    ref.startsWith("origin/") ? ref.slice("origin/".length) : null
  const fetch =
    remoteBranch === null ? "" : (
      `git fetch --no-tags origin ${remoteBranch}\n          `
    )

  return `name: crap-check history

# Generated by crap-check init. Rebuilds the complexity history of ${ref} and
# writes it back to ${isPr ? `a pull request against ${branch}` : branch}.
# History rows are ISO weeks whatever the schedule; the newest week is always
# recomputed, so a run inside a week refines that week's row.

on:
  schedule:
    - cron: "${cron}"
  workflow_dispatch:

# Nothing needs a token by default. The job asks for what it uses.
permissions: {}

concurrency:
  group: crap-check-history
  cancel-in-progress: false

jobs:
  refresh:
    name: Refresh the complexity history
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write${isPr ? "\n      pull-requests: write" : ""}
    steps:
      - uses: ${ACTIONS.checkout}
        with:
          ref: ${branch}
          # The walk reads every period's commit out of the object database.
          fetch-depth: 0
          persist-credentials: true

      - uses: ${ACTIONS.setupNode}
        with:
          node-version: 24
${installSteps(install)}
      - name: Refresh and write back${isPr ? "\n        env:\n          GH_TOKEN: ${{ github.token }}" : ""}
        run: |
          set -euo pipefail
          ${fetch}
          refresh() {
            ${cli} refresh --ref ${ref}
            git add ${outDir}
          }

          commit() {
            ${COMMIT}
          }
${isPr ? prScript(options) : pushScript(options)}
`
}

export interface PrWorkflowOptions {
  outDir: string
  cli: string
}

/** The pull-request delta comment. Reads two commits, writes nothing to the repository. */
export const renderPrWorkflow = ({
  cli,
}: PrWorkflowOptions): string => `name: crap-check pr

# Generated by crap-check init. Comments what a pull request does to the
# complexity of the codebase. Gates nothing.

on:
  pull_request:

permissions: {}

concurrency:
  group: crap-check-pr-\${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  complexity:
    name: Complexity
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # A fork gets a read-only token, so the comment would fail. A dependency bump
    # moves no complexity.
    if: >-
      github.event.pull_request.user.login != 'dependabot[bot]'
      && github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: ${ACTIONS.checkout}
        with:
          ref: \${{ github.event.pull_request.head.sha }}
          # The merge base needs the shared history.
          fetch-depth: 0
          persist-credentials: false

      - uses: ${ACTIONS.setupNode}
        with:
          node-version: 24

      - name: Measure
        env:
          BASE: \${{ github.event.pull_request.base.ref }}
        run: |
          set -euo pipefail
          ${cli} diff \\
            --base "$(git merge-base "origin/$BASE" HEAD)" \\
            --head HEAD \\
            --markdown "$RUNNER_TEMP/crap-check-report.md"
          cat "$RUNNER_TEMP/crap-check-report.md" >> "$GITHUB_STEP_SUMMARY"

      - name: Upsert the comment
        env:
          GH_TOKEN: \${{ github.token }}
          REPO: \${{ github.repository }}
          PR: \${{ github.event.pull_request.number }}
        run: |
          set -euo pipefail
          body=$(cat "$RUNNER_TEMP/crap-check-report.md")
          id=$(gh api "repos/$REPO/issues/$PR/comments" --paginate \\
            --jq '.[] | select(.body | startswith("${MARKER}")) | .id' | head -n 1)
          if [ -n "$id" ]; then
            gh api --method PATCH "repos/$REPO/issues/comments/$id" -f body="$body"
          else
            gh api --method POST "repos/$REPO/issues/$PR/comments" -f body="$body"
          fi
`
